# Generated by Django 3.0.3 on 2020-07-17 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200707_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover_photo',
            field=models.ImageField(blank=True, height_field='avatar_height', null=True, upload_to='news', width_field='avatar_width'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
