# Generated by Django 3.0.3 on 2020-07-17 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200717_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
