# Generated by Django 3.0.3 on 2020-07-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200717_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='avatar_height',
        ),
        migrations.RemoveField(
            model_name='news',
            name='avatar_width',
        ),
        migrations.AlterField(
            model_name='news',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
    ]
